Radio Module B update and xdot/sarau260 userland driver code
lab11/signpost pull request #59
Opened 2017-05-28 02:54 UTC by adkinsjd

This pull request includes the code necessary for minimal operation of the xdot and the u260 along with two minimal tests of their operation. It also includes an updated board file (the old board revision was moved to the old_revisions folder).

2017-05-28 14:58 UTC, bradjc commented on software/apps/libsignpost/sara_u260.c
> +    int clen = sprintf(c, "AT+UDELFILE=\"%s\"\r", fname);
These should be "n" functions, if for no other reason than to set a good example.

2017-05-28 14:58 UTC, bradjc commented on software/apps/libsignpost/sara_u260.c
> +
Delete extra whitespace

2017-05-28 14:58 UTC, bradjc commented on software/apps/libsignpost/xdot.h
> +int xdot_set_adr(uint8_t adr);
What does this function do?

2017-05-28 14:58 UTC, bradjc commented on software/apps/libsignpost/xdot.h
> +
A one liner comment at the top of the .h files with the name of the chip and a URL would be great.

2017-05-28 14:58 UTC, bradjc commented on software/apps/radio_module/cellular_test/main.c
> +#include <string.h>
A couple two line READMEs that explains what should happen in these tests would be great.

2017-05-28 14:58 UTC, bradjc commented on software/kernel/signpost_drivers/src/sara_u260.rs
> +        // old readline code
Don't need this old code.

2017-05-28 14:58 UTC, bradjc commented on software/kernel/signpost_drivers/src/xdot.rs
> +        // old readline code
here too

2017-05-28 23:48 UTC, adkinsjd commented
These commits should address all of Brad's comments.

2017-05-29 02:00 UTC, brghena requested changes
Overall looks really good. I've got two changes, but after those I'd say it's good to merge.

2017-05-29 02:00 UTC, brghena commented on software/apps/libsignpost/multi_console.c
> +    uint8_t* cbuf = (uint8_t*)malloc(count * sizeof(uint8_t));
Here's the malloc, but where's the free? (same goes for the other three malloc uses)

2017-05-29 02:00 UTC, brghena commented on software/kernel/signpost_drivers/src/xdot.rs
> +                            self.uart.receive_automatic(buffer, 10);
This and the `receive_automatic` call in sara_u260 have different timeouts. You should put a comment to note the difference and explain why it changed from the console driver (in whichever changed).

2017-05-29 03:45 UTC, adkinsjd commented
@brghena Your changes are in the code

2017-05-29 03:47 UTC, brghena commented
I'd say it's good to go then when it passes travis.

2017-05-29 03:57 UTC, merged